export const testProduct = {
	id: 1,
	title: 'Индейка, филе грудки на подложке замороженное "Индилайт"',
	discountPrice: 300,
	points: 160,
	price: 496,
	packagePrice: 2456,
	imagesUrl: [
		'https://i.ibb.co/zXsckbq/card-Image.png',
		'https://i.ibb.co/zXsckbq/card-Image.png',
		'https://i.ibb.co/VJtYk34/6.png',
	],
	isFavorite: false,
	rating: 4.6,
	weight: 300,
	tags: ['Хит', 'Новинка', 'Заморозка'],
	country: 'Россия',
	brand: 'Fish & More',
	type: 'Птица',
	menu: 'Банкетное меню',
	taste: 'Сырое',
	inStock: 'много',
	deliveryCharacteristics: {
		bestBefore: '1 год',
		type: 'Коробка',
		count: 10,
		palletCount: 40,
	},
};
